steps:
- name: golang
  args: ['go', 'build', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE', '.', '--build-arg', "token=$_TOKEN", '--build-arg', "gcs=$_GCS" ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE']
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE'